lib/fog/kubevirt/compute.rb
lib/fog/kubevirt/core.rb
lib/fog/kubevirt/models/compute/livevm.rb
lib/fog/kubevirt/models/compute/livevms.rb
lib/fog/kubevirt/models/compute/offlinevm.rb
lib/fog/kubevirt/models/compute/offlinevms.rb
lib/fog/kubevirt/models/compute/template.rb
lib/fog/kubevirt/requests/compute/create_offlinevm.rb
lib/fog/kubevirt/requests/compute/create_pvc.rb
lib/fog/kubevirt/requests/compute/get_livevm.rb
lib/fog/kubevirt/requests/compute/get_offlinevm.rb
lib/fog/kubevirt/requests/compute/get_template.rb
lib/fog/kubevirt/requests/compute/list_livevms.rb
lib/fog/kubevirt/requests/compute/list_offlinevms.rb
lib/fog/kubevirt/requests/compute/list_templates.rb
lib/fog/kubevirt/requests/compute/update_offlinevm.rb

This pr implements cloning of a vm from template. The change includes listing of
livevm(s) and starting offlinevm.
As part of this work we align the code to work with openshift.

Clone vm from template

---

lib/fog/compute/kubevirt/models/template.rb

Fixes https://github.com/fog/fog-kubevirt/issues/8

Specify running element for offline vm

---

lib/fog/compute/kubevirt.rb
lib/fog/compute/kubevirt/models/templates.rb
lib/fog/compute/kubevirt/models/vminstance.rb
lib/fog/compute/kubevirt/models/vminstances.rb
lib/fog/compute/kubevirt/models/vms.rb
lib/fog/compute/kubevirt/requests/create_pvc.rb
lib/fog/compute/kubevirt/requests/create_vm.rb
lib/fog/compute/kubevirt/requests/create_vminstance.rb
lib/fog/kubevirt.rb
lib/fog/kubevirt/version.rb

This PR improves and fixes exception handling issues. We make sure to handle correctly 404 when fetching collections.

Improve exception handling

---

fog-kubevirt.gemspec

https://github.com/fog/fog-kubevirt/issues/20

Bump fog-core version to 2.1.1

---

.gitignore
.travis.yml
Rakefile
fog-kubevirt.gemspec
lib/fog/kubevirt/compute/compute.rb
lib/fog/kubevirt/compute/models/service.rb
lib/fog/kubevirt/compute/models/services.rb
lib/fog/kubevirt/compute/requests/create_service.rb
lib/fog/kubevirt/compute/requests/delete_service.rb
lib/fog/kubevirt/compute/requests/get_service.rb
lib/fog/kubevirt/compute/requests/list_services.rb
spec/compute_v1alpha2_spec.rb
spec/fixtures/kubevirt/service/v1alpha2/services_crud.yml
spec/shared_context.rb
spec/spec_helper.rb

We need service support to expose ports of services such as 22 (ssh).
This is needed for vagrant-kubevirt ssh action.

Provide service support

---

lib/fog/compute/kubevirt.rb

Introduces two parameters for the kubevirt provider:
* kubevirt_verify_ssl - boolean 'true'/'false' indicates if SSL should be
used or not. Default is 'false'.
* kubevirt_cert_store - may contain either the trusted CA (pem format)
or a path to a file contains it.

Support SSL

---

lib/fog/compute/kubevirt/models/vms.rb

We need the ability to configure username and/or password when
we create a vm. This PR provides ability to pass cloud-init information.

vm: cloud-init support

---

lib/fog/compute/kubevirt/models/vm_base.rb
lib/fog/compute/kubevirt/models/vm_data.rb
lib/fog/compute/kubevirt/models/vminstance.rb

Adding detailed information of disks, volumes, interfaces and networks for VMs and Servers.

Extend VMs, VM Instances and servers

---

lib/fog/kubevirt/compute/models/vm_base.rb

deep_merge! is in Shared module so we need to include it so we can use it.

deep_merge! not available in the module

---

fog-kubevirt.gemspec

Kubeclient 4.1 includes API chunking support which helps with
performance on retrieving large collections.
https://github.com/abonas/kubeclient/pull/356

Update kubeclient to 4.1 for chunking support

---

lib/fog/compute/kubevirt.rb
lib/fog/compute/kubevirt/models/volume.rb
lib/fog/compute/kubevirt/models/volumes.rb
lib/fog/compute/kubevirt/requests/create_volume.rb
lib/fog/compute/kubevirt/requests/delete_volume.rb
lib/fog/compute/kubevirt/requests/get_volume.rb
lib/fog/compute/kubevirt/requests/list_volumes.rb
spec/fixtures/kubevirt/volume/v1alpha2/volumes_crud.yml
spec/volumes_v1alpha2_spec.rb

Based on [1], adding support for CRUD of Persistent Volumes.
[1] https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#persistentvolumespec-v1-core

Support Persistent Volumes

---

fog-kubevirt.gemspec
lib/fog/compute/kubevirt/models/vm_data.rb
lib/fog/compute/kubevirt/models/vms.rb
lib/fog/compute/kubevirt/requests/get_vminstance.rb
lib/fog/compute/kubevirt/requests/list_vms.rb

We need to align fog-kubevirt with new KubeVirt api.
Fixes: https://github.com/fog/fog-kubevirt/issues/57

Change registry to container disk

---

lib/fog/compute/kubevirt.rb

With this PR a user can use KUBECONFIG to provide config file location or
~/.kube/config will be used. This allows user to use exactly the same
authentication method as with kubectl.
:kubevirt_token is no longer required attibute and when not set config
file is used.

Backport: Introduce config file based client

---

CHANGELOG.md
lib/fog/kubevirt/version.rb

* Fix broken create VM due to API changes
* Fix VM status, nics and cloud-init to support vagrant
* Add VMI watches
* Introduce config file based client

Bump version to 0.2.1

---

lib/fog/compute/kubevirt/models/vms.rb
spec/create_vm_spec.rb
spec/fixtures/kubevirt/vm/vm_create_multi.yml
spec/fixtures/kubevirt/vm/vm_create_single.yml

This PR provides ability to create a vm with one or more pvcs.

Allow to create vm with multiple pvcs

---

CHANGELOG.md
lib/fog/kubevirt/compute/models/volume.rb
lib/fog/kubevirt/version.rb

* Replace VmVolume with Volume as main collection
* Allow to create vm with multiple pvcs
* Rename Volume to PersistentVolume
* Add support for Storage Class
* Make VmVolume a Fog model
* Extend VMs, VM Instances and servers

Bump master to 1.1.0

---

CHANGELOG.md
lib/fog/kubevirt/version.rb

* Replace VmVolume with Volume as main collection
* Allow to create vm with multiple pvcs
* Rename Volume to PersistentVolume
* Add support for Storage Class

Bump version to 0.3.0

---

CHANGELOG.md
lib/fog/kubevirt/version.rb

* Support SSL
* Validate namespace exists
* Make VmNic fog model
* Minor bug

Bump version to 1.1.1

---

lib/fog/kubevirt/compute/compute.rb
lib/fog/kubevirt/compute/requests/create_pvc.rb
lib/fog/kubevirt/compute/requests/create_vm.rb
lib/fog/kubevirt/compute/requests/get_server.rb
lib/fog/kubevirt/compute/requests/list_networkattachmentdefs.rb
lib/fog/kubevirt/compute/requests/list_storageclasses.rb
lib/fog/kubevirt/compute/requests/update_vm.rb

Add some mocks for foreman_kubevirt tests.

Adding mocks

---

CHANGELOG.md
lib/fog/kubevirt/version.rb

* Replace state with phase of Server model
* Add mocks

Bump version to 1.2.0

---

CHANGELOG.md
lib/fog/kubevirt/version.rb

* Do not rely on attributes defaults
* Populate PVC attributes for Volume

Bump version to 1.2.4

---

lib/fog/kubevirt/compute/requests/get_server.rb
lib/fog/kubevirt/compute/requests/list_servers.rb
spec/fixtures/kubevirt/server/server_ops.yml
spec/unit/server_v1alpha3_spec.rb

We need to get networking details from vmi object.
Fixes: https://bugzilla.redhat.com/1700815

servers: update networks from vmi

---

lib/fog/kubevirt/compute/compute.rb
lib/fog/kubevirt/compute/models/pvcs.rb
spec/integration/pvcs_spec.rb
spec/unit/unit_converter_spec.rb

We need to make sure that values accepted are correct before we
call the api to create pvc.

pvc: validate request size and limit

---

fog-kubevirt.gemspec

I run tests and integration tests. I do not see any regressions.

gemspec: update kubeclient version

---

CHANGELOG.md
lib/fog/kubevirt/version.rb

* Add validattion for PVC request size and limit
* Update networks from vmi on Server
* Update kubeclient version to 4.3.0

Bump version to 1.2.5

---

spec/integration/net-attach-def_spec.rb

This PR adds integration tests for network attachement definitions.

tests: Add network attachement definitions

---

lib/fog/kubevirt/compute/compute.rb
lib/fog/kubevirt/compute/models/vm.rb
lib/fog/kubevirt/compute/models/vminstances.rb
lib/fog/kubevirt/compute/models/vms.rb
spec/integration/mac_vmi_spec.rb

In the tests we create vm and we use api for vmi/server to start the vm. We wait on it to be `Running` and we assert spec with mac address.

tests: provision vmi/server and check mac

---

lib/fog/kubevirt/compute/models/persistentvolume.rb
lib/fog/kubevirt/compute/models/persistentvolumes.rb
lib/fog/kubevirt/compute/models/storageclass.rb
spec/integration/volumes_spec.rb

In this PR we provide persistent volume create, read and delete tests.

tests: add volumes

---

lib/fog/kubevirt/compute/compute.rb
lib/fog/kubevirt/compute/models/pvcs.rb
lib/fog/kubevirt/compute/models/template.rb
lib/fog/kubevirt/compute/utils/exception_wrapper.rb
lib/fog/kubevirt/compute/utils/unit_converter.rb
spec/unit/unit_converter_spec.rb

Shared module grew over time and many of the classes and constants
should not be there.

compute: rearrange utils

---

lib/fog/kubevirt.rb
lib/fog/kubevirt/compute/compute.rb
lib/fog/kubevirt/compute/requests/create_networkattachmentdef.rb
lib/fog/kubevirt/compute/requests/create_persistentvolume.rb
lib/fog/kubevirt/compute/requests/create_pvc.rb
lib/fog/kubevirt/compute/requests/create_service.rb
lib/fog/kubevirt/compute/requests/create_storageclass.rb
lib/fog/kubevirt/compute/requests/create_vm.rb
lib/fog/kubevirt/compute/requests/create_vminstance.rb
lib/fog/kubevirt/compute/utils/exception_wrapper.rb
spec/integration/net-attach-def_spec.rb

We introduce exception hierarchy and we raise correct error in single place based on `error_code` we get.

exception handling improvements

---

CHANGELOG.md
lib/fog/kubevirt/version.rb

* Log exception for client errors
* Support memory unit in create_vm
* Exception handling improvements
* Add tests to allow configure namespace
* Add tests for provision vmi/server and check mac
* Add volumes tests
* Refactor utils module
* Add network attachement definitions tests

Bump version to 1.3.0

---

CHANGELOG.md
lib/fog/kubevirt/version.rb

Signed-off-by: Moti Asayag <masayag@redhat.com>

Bump version 1.3.5

---

CHANGELOG.md
lib/fog/kubevirt/version.rb

Signed-off-by: Moti Asayag <masayag@redhat.com>

Bump version to 1.3.6

---

.github/workflows/ci.yaml

I'm only testing with 2.7 here so that it can go green, I'll push a follow-up PR that shows the failure with ruby3+

Add a simple github-actions workflow
