fog/fog-kubevirt

examples/sample.rb, lib/fog/compute/kubevirt.rb, lib/fog/compute/kubevirt/models/offlinevm.rb, lib/fog/kubevirt/version.rb
Since kubevirt v0.4.0 there is no longer a need to create the live vm entity explicitly.
=> Remove explicit vm creation

CHANGELOG.md, lib/fog/compute/kubevirt.rb, lib/fog/compute/kubevirt/models/livevm.rb, lib/fog/compute/kubevirt/models/livevms.rb, lib/fog/compute/kubevirt/models/nodes.rb, lib/fog/compute/kubevirt/models/offlinevms.rb, lib/fog/compute/kubevirt/models/templates.rb, lib/fog/compute/kubevirt/requests/list_livevms.rb, lib/fog/compute/kubevirt/requests/list_nodes.rb, lib/fog/compute/kubevirt/requests/list_offlinevms.rb, lib/fog/compute/kubevirt/requests/list_templates.rb, lib/fog/kubevirt/version.rb
We assumed about vm status based on part of the flow we were in.
This PR uses vm status as collected from kubevirt.
=> Use vm status provided by kubevirt

lib/fog/compute/kubevirt.rb
Without setting the proper expected kind (VirtualMachineInstance), no VM Instance notices were processed.
Updating to the expected kind will fix that.
=> Fix expected vm instance type in notice

CHANGELOG.md, lib/fog/compute/kubevirt/models/template.rb, lib/fog/kubevirt/version.rb
The PR adds support for both types of parameters: ${PARAM} and ${{PARAM}} by replacing both with value from the parameters section if such parameter exists.
=> Support openshfit templates parameters

fog-kubevirt.gemspec
Allow `~>` to follow a good practice by constraining on major and minor versions and loosen up on the bug version.
It also allows to use fog-core version 2.1.0 which used by other Fog projects before switching to coming release which will carry namespace changes which are going to be part of a new Major version release.
=> Loosen fog-core dependency

lib/fog/kubevirt.rb, lib/fog/kubevirt/compute/compute.rb, lib/fog/kubevirt/compute/models/vm.rb, lib/fog/kubevirt/compute/models/vms.rb
We want to know whether vm is in running state. As well as we want to be
more tolerant in terms of missing attribute during parsing process.
We add ability to create a vm without having a template.
=> vm: add status property

CHANGELOG.md, lib/fog/kubevirt/version.rb
Since fog-core was promoted to 2.x, master is bumped as well.
This is designed to allow a clear separation between core-1.45
branch which is based on fog-core-1.45.0.
=> Bump version to 1.x.x

lib/fog/kubevirt/compute/models/vm.rb
It is possible to run create a vm [1] without memory requirement which
we need to handle.
[1] https://github.com/kubevirt/demo/blob/master/manifests/vm.yaml
=> vm: memory is not required

lib/fog/kubevirt/compute/models/vms.rb
We need the ability to configure username and/or password when
we create a vm. This PR provides ability to pass cloud-init information.
=> vm: cloud-init support

fog-kubevirt.gemspec
We need to update kubeclinet to the latest version.
=> gemspec: use latest kubeclient

lib/fog/compute/kubevirt/models/vms.rb
In foreman, the VM name may contain also the domain name.
When setting this name as the volume name, running the VM fails
with the following error:
```
Warning  FailedCreate  21s               virtualmachine-controller
Error creating pod: Pod "virt-launcher-vmi-multus-lqcwz" is invalid:
spec.containers[0].name: Invalid value: "volumevmi-multus.example.com":
a DNS-1123 label must consist of lower case alphanumeric characters or '-',
and must start and end with an alphanumeric character (e.g. 'my-name',
or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?')
```
Therefore the dots from FQDN VM name cannot be part of the volume name.
The patch assumes the name without the domain should be sufficient.
For VM named `stacy-bulgin.example.com` the created volume name is …
=> Volume name should respect restrictions

lib/fog/compute/kubevirt/models/server.rb
The IP Address is not reported for non-default networks,
therefore removing the IP-address availability from the
condition to rely on as server readiness.
=> Do not rely on IP Address for VM readiness

fog-kubevirt.gemspec, lib/fog/kubevirt/compute/compute.rb
With this PR a user can use KUBECONFIG to provide config file location or
~/.kube/config will be used. This allows user to use exactly the same
authentication method as with kubectl.
`:kubevirt_token` is no longer required attibute and when not set config
file is used.
=> Introduce config file based client

CHANGELOG.md, lib/fog/kubevirt/version.rb
Foreman expects vm.volumes to return an array of Fog::Model.
For that purpose, VmVolume is changed to inherit from it.
=> Make VmVolume a Fog model

CHANGELOG.md, lib/fog/kubevirt/version.rb
Includes the following changes:
* Detect kubevirt api version
* Change registry to container disk
* Support Persistent Volume Claims
* Bump kubeclient to 4.1.2
* Support Persistent Volumes
* Volume name should respect restrictions
=> Bump version to 0.2.0

lib/fog/kubevirt/compute/compute.rb
When we wanted to watch VMI we actually watched VM objects. This PR
fixes the issue.
=> Watch VMIs

lib/fog/compute/kubevirt/models/vms.rb
Recent VM API changes removed the volumeName from the disk section.
Instead, matching a dist to its volume is done by the disk name.
Therefore, the same value should be used for as volume name under
the volumes section and also as the disk name.
=> Fix broken vm creation

CHANGELOG.md, lib/fog/kubevirt/version.rb
* Asdd Watch VMIs
* Differentiate status and state
* Change kubevirt api version
* Change registry to container disk
* Remove bundler dependency
* Bump kubeclient to 4.1.2
* Support Persistent Volume Claims
* Support Persistent Volumes
* Support networks and interfaces
* Volume name should respect restrictions
* Introduce config file based client
* Add vm cloud-init support
* server and servers
* Allow local Gemfile.dev.rb
* Support services
* Make VM memory optional
=> Bump version to 1.0.2

lib/fog/compute/kubevirt.rb, lib/fog/compute/kubevirt/models/vm_base.rb, lib/fog/compute/kubevirt/models/vm_data.rb, lib/fog/compute/kubevirt/models/vminstance.rb, lib/fog/compute/kubevirt/models/vms.rb, lib/fog/compute/kubevirt/models/volume.rb, lib/fog/compute/kubevirt/models/volumes.rb, lib/fog/compute/kubevirt/requests/delete_vm.rb, lib/fog/compute/kubevirt/requests/delete_vminstance.rb, lib/fog/compute/kubevirt/requests/list_volumes.rb, spec/create_vm_spec.rb, spec/fixtures/kubevirt/pvc/pvcs_crud.yml, spec/fixtures/kubevirt/vm/vm_create_multi.yml, spec/fixtures/kubevirt/vm/vm_create_single.yml, spec/pvcs_v1alpha2_spec.rb
The 'volumes' collection will allow to list all volumes in the system
that are backed by a PVC or to list all of vm volumes, if given a vm
name while trying to list the volumes.
The Volume class will be used also as a parameter for passing volume for
a virtual machine create request, so additional information could be
specified such as 'bus' and 'boot_order' to determine how the volume
should be configured for the vm.
With this PR also fixed the delete_vm service so cleanup after tests
will work as expected when recording VCR for specs.
=> Replace VmVolume with Volume as main collection

lib/fog/kubevirt/compute/compute.rb
The fog-kubevirt should produce the same error for various failures to allow a proper exception handling by the clients.
=> Wrap version detection with ClientError

lib/fog/kubevirt/compute/requests/get_vm.rb, lib/fog/kubevirt/compute/requests/get_vminstance.rb
After enabling mock mode using `Fog.mock!` we want to be able to
fetch fake test vm. This PR provides this capability.
=> Mock: fetch vm

lib/fog/kubevirt/compute/compute.rb
kubevirt_namespace is a require parameter for creating the kubevirt compute service.
There is a need to verify the namespace exists on the cluster, therefore a check for it is being added to the validation method.
=> Validate namespace exists

lib/fog/kubevirt/compute/compute.rb
In order to reflect the exact failure reason, the server should be
tested for connectivity before examining its capabilities.
=> Verify server is accessible before other validations

lib/fog/kubevirt/compute/models/server.rb
Server.state has a specific semantic in foreman-kubevirt that needs to
be provided on foreman-kubevirt side. This behavior cannot be overridden
if the Server model contains such property.
Therefore renaming state to phase, which also reflects the property
nature.
=> Replace state with phase

lib/fog/kubevirt/compute/models/vm_base.rb, lib/fog/kubevirt/compute/models/vm_parser.rb, lib/fog/kubevirt/compute/models/vminstance.rb, spec/vm_parse.rb
In status section kubevirt reports mac addresses for specific interfaces.
This PR collects those addresses and store them in vminc class.
=> Use mac address reported by kubevirt

CHANGELOG.md, lib/fog/kubevirt/version.rb
* Use mac address reported by KubeVirt
* Do not pass an empty selector
* Populate PVC for VM volume
=> Bump version to 1.2.1

lib/fog/kubevirt/compute/models/vm_parser.rb, lib/fog/kubevirt/compute/requests/get_server.rb, spec/vm_parse.rb
There is time when vmi is not running yet. We need to make sure to
handle this scenario when parsing interfaces.
=> Handle scheduled vmis

lib/fog/kubevirt/compute/models/servers.rb, lib/fog/kubevirt/compute/models/vm_base.rb, lib/fog/kubevirt/compute/models/vm_parser.rb, lib/fog/kubevirt/compute/models/vms.rb
* Using attributes defaults creates a shared object for all of the model
instances. This is undesired behavior, but it is by design.
This PR will initialize the collections to their defaults, and also will
update the parsing methods to return the expected values when being
called (and empty array instead of an empty hash).
=> Do not rely on attributes defaults

spec/integration/mac_vmi_spec.rb, spec/integration/pvcs_spec.rb, spec/integration/shared_context.rb
This PR provides ability to customize namespace before running integration tests. In this way we can make sure that not only `default` namespace works well.
=> tests: Allow to configure namespace

CHANGELOG.md, lib/fog/kubevirt/version.rb
* Fixes #1728671 - fix undefined boot_order
* Add VNC console details function
=> Bump version 1.3.2

lib/fog/kubevirt/compute/compute.rb
Adding an option to choose the kubevirt API version when initializing the provider, since there is a BZ in kubevirt reporting the preferred version: (the preferred version should be v1alpha3 and not v1, since v1 is broken)
```
[cnv-qe-jenkins@cnv-executor-ginger5 ~]$ kubectl get --raw /apis/kubevirt.io | python -m json.tool  
{
"apiVersion": "v1",
"kind": "APIGroup",
"name": "kubevirt.io",
"preferredVersion": {
"groupVersion": "kubevirt.io/v1",
"version": "v1"
},
"versions": [
{
"groupVersion": "kubevirt.io/v1",
"version": "v1"
},
{
"groupVersion": "kubevirt.io/v1alpha3",
"version": "v1alpha3"
},
{
"groupVersion": "kubevirt.io/v1alpha1",
"version": "v1alpha1"
}
]
}
```
=> Add option to specify the kubevirt API version

fog-kubevirt.gemspec
I wasn't sure if you'd prefer bumping kubeclient to the current version (4.6.0) or opening up the fog-kubevirt gemspec to allow for the bundling program to dictate the kubeclient version they would like.  I'll leave that up to the maintainers
=> Allow for newer versions of kubeclient

lib/fog/kubevirt/compute/compute.rb, lib/fog/kubevirt/compute/requests/get_template.rb, lib/fog/kubevirt/compute/requests/list_templates.rb
The OpenShift /oapi endpoint has been discontinued and the API group for templates is `template.openshift.io/v1`
This fixes the 404 exception when listing templates on modern openshift 4 clusters
Tested with:
OpenShift version: 4.9.12
Kubernetes version: v1.22.3+e790d7f
OpenShift Virtualization: 4.9.2
=> Fix get_templates API group

lib/fog/kubevirt/compute/models/services.rb, lib/fog/kubevirt/compute/models/templates.rb, lib/fog/kubevirt/compute/models/vminstances.rb, lib/fog/kubevirt/compute/models/vms.rb
If an API call raises a `Fog::Kubevirt::Errors::ClientError` exception due to a 404 the `def all` methods are catching that exception and setting the result to `[]`.
Later on the method then tries to set the `@kind` and `@resource_version` instance variables to e.g. `vms.kind` and `vms.resource_version` which fails if `vms = []`.
Fixes https://github.com/fog/fog-kubevirt/issues/148
=> Fix undefined method exception handling 404 error

.github/workflows/ci.yaml, fog-kubevirt.gemspec
I also had to bump rake to 13 from 12 to allow for newer a http gem, http 4.4 wouldn't build on ruby3
=> Test with ruby 3.0, 3.1, and 3.2
